### ISSUE TITLE
Long-term planning metabug

### ISSUE THREAD

**Issue by CensoredUsername** [CensoredUsername/dynasm-rs#12]
This bug contains a listing of improvements to be made to the library, sorted by priority. 

General

High

- [ ] Modularizing different assembly dialects. Currently the only supported assembly language is x64, both in the plugin and the runtime. For the plugin the assembly language to use should be a setting determined by directives or crate attributes preferably, while for the runtime having each dialect in a separate submodule implementing the same traits would be the way to go. As for internal plugin infrastructure, it seems best to me that different assembly languages have completely separate parsing and compiling implementations (dialects like x86/x64 could share them), but all of them end up producing something that a common serialization module can understand.
- [ ] x86 support
- [ ] x64 support needs to be tested thoroughly.
- [ ] a comprehensive testing framework that not only allows to test the current implementation, but also future extensions with reference tools.

Medium

- [ ] Toolchain improvement: as the project consists out of several different crates in subfolders, building and testing everything is less than ergonomic currently.
- [ ] Improving the quality of error messages. Mainly the error messages when an instruction isn't found or when an instruction variant doesn't exist are a little bare-bones
- [ ] Currently, no checking is done on redundant prefixes or impossible prefixes.
- [ ] For several ops (like x64 movsx) default to a certain argument size if the size of an argument isn't correctly specified. This should result in an error.
- [ ] ARM support
- [ ] Assembler::align is hardcoded to align as to what is required by x64.
- [ ] Support in the runtime to keep track of all relocations caused by labels. This is important on the roadmap for x86 support, or x64 code only using a 32-bit address space.
- [ ] Review the x64 operand size determination code and how it deals with immediate sizes.

Low

- [ ] x64/x86 address displacement size hint
- [ ] automatic size optimization for constant immediate / displacement arguments
- [ ] AVX-512 support
- [ ] MIPS support

Assembly dialect specific

- x64

  - [ ] Jumps with 16-bit relative offsets are illegal in long mode.

**Comment by mlgiraud** [comment]
Is there any plan for the avx-512 support? Are there some pointers you can give me on how you would want this to be implemented? I could try and have a go at it (or one of my colleagues).

**Comment by CensoredUsername** [comment]
@mlgiraud Hi! Currently I'm pretty busy IRL to the point where my investment in this project is just trying to keep it working at the current level. That said, I'd be very happy to see AVX-512 support happening, so if I can assist with getting such a pull request done I'd be very happy.

That said, the x86/AMD64 backend is the first assembler that I built for this project and it does show. The backend is a little bit of a mess (and granted, that's also because x86/AMD64 is a significant mess). And with all the features AVX-512 piles in, it might need some refactoring to properly handle it without adding even more edge cases to it.

If that doesn't scare you off, I'd be very happy to sit down and try work out or discuss a preliminary design for how to integrate it.

**Comment by mlgiraud** [comment]
I'll have a look first and check if i have time to implement this myself and otherwise pass it on to a colleague. I'd come back to you once i have a better understanding of what has to be done. Sound good?

What is your stance on generated code? If you are against having that in this codebase i fully understand and will keep that out of any contributions. But better ask first, right?

> that's also because x86/AMD64 is a significant mess

Oh how right you are.

**Comment by CensoredUsername** [comment]
>I'd come back to you once i have a better understanding of what has to be done. Sound good?

Sure, no problem

>What is your stance on generated code? If you are against having that in this codebase i fully understand and will keep that out of any contributions. But better ask first, right?

Currently, there's no AI-generated code in the codebase. I'm not necessarily opposed to it by default, but the way most of the current models have been trained leaves quite a foul taste in my mouth, i.e. without explicit permission by authors, and little respect for licensing (i.e. just training on GPL'd code and then being used to, with little effort, spit out practically identical code but free of the copyleft license).

If you know of a model that was trained on ethically obtained data, I wouldn't mind that. But otherwise I'd prefer not.

>Oh how right you are.

It's a beautiful example of the adage "If the hole is to deep to get out of, you can only keep digging"

**Comment by mlgiraud** [comment]
> > I'd come back to you once i have a better understanding of what has to be done. Sound good?
> 
> Sure, no problem

This will probably take some time, i'll let you know. If you have any heads up things let me know, otherwise i will just dive in. I'll also take a look at my other endbr64 issue while i'm at it.

> > What is your stance on generated code? If you are against having that in this codebase i fully understand and will keep that out of any contributions. But better ask first, right?
> 
> Currently, there's no AI-generated code in the codebase. I'm not necessarily opposed to it by default, but the way most of the current models have been trained leaves quite a foul taste in my mouth, i.e. without explicit permission by authors, and little respect for licensing (i.e. just training on GPL'd code and then being used to, with little effort, spit out practically identical code but free of the copyleft license).

I have a different opinion on this, but thats a whole other discussion. The main point here is that i want to respect your decision on this as the maintainer, which is why i am asking. I will not be contributing any LLM generated code.

> If you know of a model that was trained on ethically obtained data, I wouldn't mind that. But otherwise I'd prefer not.

Unfortunately i don't think there is one that is actually usable, and i don't think there ever will be due to the sheer volume of data needed to get good results. If you find anything do let me know.

> > Oh how right you are.
> 
> It's a beautiful example of the adage "If the hole is to deep to get out of, you can only keep digging"

Maybe i will find some gold, who knows?

**Comment by CensoredUsername** [comment]
There's no immediate things I'm planning except for soonish having to migrate off of proc-macro2 (There's a maintained fork, just seeing if it gains traction).

As for what work would need to be done: as a first step, the parser will need to be modified to accept the new syntax that avx-512 brings (mask register syntax, extra register families, zeroing masking, broadcasting). This'll probably involve a little parser hacking to capture `{ reg_name }` before trying to parse it as an expression as a fallback, which should be pretty similar to how memory references get recognized. A few new AST nodes will probably be needed to be introduced, but this part shouldn't be that hard.

The big changes would have to be to the compiler. Which is a little bit of a mess right now. When I started the project I had some preconceptions of regularity in the instruction set, which is why I wrote the compiler as one that goes straight from the AST to the instruction encoding. If I were to write it now, I'd probably have done it differently. The ARM/RISCV backends I wrote later use a two-stage approach in which the first stage matches the operand, and splits complex instruction encodings into sets of simpler argument chunks. Then a second compiler stage encodes those arguments into an actual instruction encoding with much more flexible logic.

This would be a pretty big rewrite, but since AVX-512 introduces yet another way of encoding instructions with even more funny limitations (like certain registers sharing the upper bit of their encoding), integrating this into the current parser with even more flags would just make the code increasingly more fragile.

Outside of that, the architecture of dynasm-rs really isn't that difficult. You want to look into `plugin/src/arch/x64`. Each architecture has their own parser that gets dispatched to on a line basis depending on the active architecture. There's some shared code for the output serialization, but outside of that the thing is pretty self-contained. Feel free to ask anything if you have questions too!

>I have a different opinion on this, but thats a whole other discussion. The main point here is that i want to respect your decision on this as the maintainer, which is why i am asking. I will not be contributing any LLM generated code.

Thanks, I sincerely appreciate being asked up front.
